### ISSUE TITLE
Error when opening Social

### ISSUE THREAD

**Issue by radicaled06** [mikepauer/Carbonite.Social#1]
This happens when trying to open the Carbonite social window. The default Blizz one opens instead and I receive this error.

Date: 2017-09-02 20:27:47
ID: 1
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Social\NxSocial.lua line 780:
   attempt to call method 'RegisterEvent' (a nil value)
Debug:
   [C]: RegisterEvent()
   Carbonite.Social\NxSocial.lua:780: Create()
   Carbonite.Social\NxSocial.lua:635: ShowUIPanel()
   Carbonite.Social\NxSocial.lua:2651:
      Carbonite.Social\NxSocial.lua:2648
   [C]: ?
   [C]: ShowUIPanel()
   ..\FrameXML\FriendsFrame.lua:1070: ToggleFriendsFrame()
   [string "TOGGLESOCIAL"]:1:
      [string "TOGGLESOCIAL"]:1
Locals:

AddOns:
  Carbonite, v7.3.0
  CarboniteInfo, v7.3.0
  CarboniteNotes, v7.3.0
  CarboniteQuests, v7.3.0
  CarboniteSocial, v7.3.0
  CarboniteWarehouse, v7.3.0

**Comment by qlesz** [comment]
got the same error:
Date: 2017-09-03 12:44:06
ID: 4
Error occured in: Global
Count: 1
Message: ..\AddOns\Carbonite.Social\NxSocial.lua line 780:
   attempt to call method 'RegisterEvent' (a nil value)
Debug:
   Carbonite.Social\NxSocial.lua:780: Create()
   Carbonite.Social\NxSocial.lua:635: ShowUIPanel()
   Carbonite.Social\NxSocial.lua:2651:
      Carbonite.Social\NxSocial.lua:2648
   [C]: ?
   [C]: ShowUIPanel()
   ..\FrameXML\FriendsFrame.lua:1081: ToggleFriendsFrame()
   ..\FrameXML\QuickJoinToast.lua:304:
      ..\FrameXML\QuickJoinToast.lua:298
Locals:
self = <table> {
 GetPunkPasteInfo = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2070
 Punks = <table> {
 }
 PCloseWindows = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2668
 RestoreFriendsFrame = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:691
 OnUpdate = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:867
 SetCols = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:518
 Create = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:753
 OnTabBar = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:921
 Show = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:720
 PunksActive = <table> {
 }
 OnChat_msg_addon = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:510
 PanelTemplates_SetTab = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:905
 PHideUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2660
 GotoPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2053
 Win = <table> {
 }
 List = <table> {
 }
 PreCombatHide = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:733
 PunkNewDir = 35.481487058824
 AddLocalPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1730
 DecodeComRcvPunks = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1688
 LastLocalPunk = "Radburn"
 OnFriendListUpdate = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:851
 NoShow = true
 Init = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:558
 Cols = <table> {
 }
 PShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:2648
 PunksHUD = <table> {
 }
 UpdateIcons = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1911
 HideUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:672
 CalcPunks = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1885
 OnUpdateTimer = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1870
 GetPunk = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:1807
 ShowBlizzTabs = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:982
 OnWin = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:844
 ShowUIPanel = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:611
 TeamHUD = <table> {
 }
}
tbH = 22
win = <table> {
 TitleFStr = <table> {
 }
 BorderW = 7
 BorderH = 7
 ButClose = <table> {
 }
 Border = true
 BackgndAlphaDiff = 0.35
 BackgndAlphaMin = 0.65
 UserFunc = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:844
 BackgndFadeOut = 0.75
 SaveData = <table> {
 }
 ButMaxer = <table> {
 }
 TitleH = 12
 TitleLineH = 10
 Maxer = true
 Closer = true
 User = <table> {
 }
 LayoutMode = ""
 MovSizing = false
 BackgndFadeTarget = 0
 TopH = 19
 ChildFrms = <table> {
 }
 BackgndFadeIn = 1
 Name = "NxSocial"
 Frm = NxSocial {
 }
 BackgndFade = 0.01
 TitleLines = 1
 ButW = 12.5
 Sizeable = true
}
frm = NxSocial {
 0 = <userdata>
 NxWin = <table> {
 }
}
(*temporary) = nil
(*temporary) = <table> {
 TitleFStr = <table> {
 }
 BorderW = 7
 BorderH = 7
 ButClose = <table> {
 }
 Border = true
 BackgndAlphaDiff = 0.35
 BackgndAlphaMin = 0.65
 UserFunc = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:844
 BackgndFadeOut = 0.75
 SaveData = <table> {
 }
 ButMaxer = <table> {
 }
 TitleH = 12
 TitleLineH = 10
 Maxer = true
 Closer = true
 User = <table> {
 }
 LayoutMode = ""
 MovSizing = false
 BackgndFadeTarget = 0
 TopH = 19
 ChildFrms = <table> {
 }
 BackgndFadeIn = 1
 Name = "NxSocial"
 Frm = NxSocial {
 }
 BackgndFade = 0.01
 TitleLines = 1
 ButW = 12.5
 Sizeable = true
}
(*temporary) = "FRIENDLIST_SHOW"
(*temporary) = <function> defined @Interface\AddOns\Carbonite.Social\NxSocial.lua:851
(*temporary) = "attempt to call method 'RegisterEvent' (a nil value)"
L = <table> {
 Remove Pal And Friend = "Remove Pal And Friend"
 number of
AddOns:
  Swatter, v7.4.5714 (TasmanianThylacine)
  Atlas, vv1.43.01
  AtlasBurningCrusade, vv1.43.00
  AtlasCataclysm, vv1.43.00
  AtlasClassicWoW, vv1.43.00
  AtlasClassOrderHalls, vv1.43.00
  AtlasDungeonLocs, vv1.43.00
  AtlasLegion, vv1.43.00
  AtlasMistsofPandaria, vv1.43.00
  AtlasOutdoorRaids, vv1.43.00
  AtlasScenarios, vv1.43.00
  AtlasWarlordsofDraenor, vv1.43.00
  AtlasWorldEvents, vv3.23
  AtlasWrathoftheLichKing, vv1.43.00
  AtlasLoot, vv8.06.00
  AtlasLootBurningCrusade, vv8.06.00
  AtlasLootCataclysm, vv8.06.00
  AtlasLootClassic, vv8.06.00
  AtlasLootLegion, vv8.06.00
  AtlasLootMistsofPandaria, vv8.06.00
  AtlasLootWarlordsofDraenor, vv8.06.00
  AtlasLootWrathoftheLichKing, vv8.06.00
  AtlasMajorCitiesEnhanced, vv1.15
  AucAdvanced, v7.4.5714 (TasmanianThylacine)
  AucFilterBasic, v7.4.5714 (TasmanianThylacine)
  AucFilterOutlier, v7.4.5714.5459(7.4/embedded)
  AucMatchUndercut, v7.4.5714.5585(7.4/embedded)
  AucScanData, v7.4.5714 (TasmanianThylacine)
  AucStatHistogram, v7.4.5714 (TasmanianThylacine)
  AucStatiLevel, v7.4.5714 (TasmanianThylacine)
  AucStatPurchased, v7.4.5714 (TasmanianThylacine)
  AucStatSales, v7.4.5714.5598(7.4/embedded)
  AucStatSimple, v7.4.5714 (TasmanianThylacine)
  AucStatStdDev, v7.4.5714 (TasmanianThylacine)
  AucStatWOWEcon, v7.4.5714.5613(7.4/embedded)
  AucUtilAHWindowControl, v7.4.5714.5575(7.4/embedded)
  AucUtilAppraiser, v7.4.5714.5704(7.4/embedded)
  AucUtilAskPrice, v7.4.5714.5599(7.4/embedded)
  AucUtilAutoMagic, v7.4.5714.5686(7.4/embedded)
  AucUtilCompactUI, v7.4.5714.5694(7.4/embedded)
  AucUtilEasyBuyout, v7.4.5714.5576(7.4/embedded)
  AucUtilFixAH, v7.4.5714 (TasmanianThylacine)
  AucUtilItemSuggest, v7.4.5714.5651(7.4/embedded)
  AucUtilPriceLevel, v7.4.5714.5633(7.4/embedded)
  AucUtilScanButton, v7.4.5714.5631(7.4/embedded)
  AucUtilScanFinish, v7.4.5714.5588(7.4/embedded)
  AucUtilScanProgress, v7.4.5714.4979(7.4/embedded)
  AucUtilScanStart, v7.4.5714.5347(7.4/embedded)
  AucUtilSearchUI, v7.4.5714.5710(7.4/embedded)
  AucUtilSimpleAuction, v7.4.5714.5705(7.4/embedded)
  AucUtilVendMarkup, v7.4.5714.4828(7.4/embedded)
  Babylonian, v5.1.DEV.332(/embedded)
  BadBoy, vv7.3.1
  BadBoyCCleaner, vv7.3.0
  Bartender4, v4.7.10
  BeanCounter, v7.4.5714 (TasmanianThylacine)
  BuyEmAll, v3.3.5
  Carbonite, v7.3.0
  CarboniteInfo, v7.3.0
  CarboniteNotes, v7.3.0
  CarboniteQuests, v7.3.0
  CarboniteSocial, v7.3.0
  CarboniteWarehouse, v7.3.0
  CarboniteWeekly, v7.3.0
  ClassOrderHallsComplete, v1.26
  Configator, v5.1.DEV.406(/embedded)
  CTATracker, v
  DBMCore, v7.3.1
  DBMDefaultSkin, v
  DBMPartyCataclysm, v
  DBMStatusBarTimers, v
  DebugLib, v5.1.DEV.337(/embedded)
  Enchantrix, v7.4.5714 (TasmanianThylacine)
  EnchantrixBarker, v7.4.5714 (TasmanianThylacine)
  epgp, vv5.12.13
  epgplootmaster, v6.71
  epgplootmasterml, v6.71
  GottaGoFast, v26500
  GottaGoFastHistory, v26500
  HandyNotes, vv1.4.15
  HandyNotesBrokenShore, vv1.21
  HandyNotesDraenorTreasures, v1.20a
  HandyNotesLegionTreasures, v1
  LibExtraTip, v5.12.DEV.423(/embedded)
  MoveAnything, v16.2.2
  OmniCC, v7.3
  Overachiever, v0.99.8
  OverachieverTabs, v0.99.8
  Pawn, v2.2.13
  PersonalLootHelper, v1.32
  Postal, vv3.5.8
  Prat30, vr1078      
  Prat30Libraries, v
  ReputationBars, v7.3.0
  Skada, v1.7.2
  Skillet, v3.26
  SlideBar, v7.4.5714 (TasmanianThylacine)
  Stubby, v7.4.5714 (TasmanianThylacine)
  TellMeWhen, v8.4.2
  TellMeWhenOptions, v
  TipHelper, v5.12.DEV.405(/embedded)
  WeakAuras, v2.4.21
  WorldQuestGroupFinder, v0.27
  WorldQuestTracker, v
  WoWProgressLink, v1.21
  BlizRuntimeLib_enUS v7.3.0.70300 <none>
  (ck=e1a)

Carb installed via curse with alpha version installation on on every module

**Comment by mikepauer** [comment]
Corrected

**Comment by qlesz** [comment]
Look like it's ok now. Can you update it on curse aswell? It's still bugged version (even with alpha release on). I've tried it today and had to install directly from github.

**Comment by IrcDirk** [comment]
Same versions on Curse Alpha as here:

GitHub: e19bdc05dd4e5572f2ed02efa214b767decc3337
CurseForge: e19bdc05dd4e5572f2ed02efa214b767decc3337 (https://wow.curseforge.com/projects/carbonite-social/files/2475106)

**Comment by qlesz** [comment]
well for some reason when i install it via curse client it doesn't see this alpha version https://1drv.ms/i/s!AjvnngFuVS4XhG3e0ScYeIHLRgi2

**Comment by mikepauer** [comment]
Curse has known issues with sync between curse and curseforge currently.
It's all being done manually by curse staff right now.. alphas may not have
same priority as releases for them

**Comment by qlesz** [comment]
So if we know that this commit is working fine and fix the previous problems why can't you issue this on curse as release?
