### ISSUE TITLE
friends list bug

### ISSUE THREAD

**Issue by qlesz** [mikepauer/Carbonite.Social#3]
Issue:
Error Message: ..\AddOns\Carbonite.Social\NxSocial.lua line 1339:
   attempt to call global 'GetNumFriends' (a nil value)

Solution:
change old function call **local cnt = GetNumFriends()** to new one  **local cnt = C_FriendList.GetNumFriends()**
(lines 1339 and 1445)

**Comment by IrcDirk** [comment]
Fixed.
